// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WizardDataInfo.proto

package com.wizard.protobuf.data;

public final class WizardData {
	private WizardData() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface WizardDataInfoOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int32 id = 1;
		boolean hasId();

		int getId();

		// optional string name = 2;
		boolean hasName();

		String getName();

		// repeated string data = 3;
		java.util.List<String> getDataList();

		int getDataCount();

		String getData(int index);
	}

	public static final class WizardDataInfo extends
			com.google.protobuf.GeneratedMessage implements
			WizardDataInfoOrBuilder {
		// Use WizardDataInfo.newBuilder() to construct.
		private WizardDataInfo(Builder builder) {
			super(builder);
		}

		private WizardDataInfo(boolean noInit) {
		}

		private static final WizardDataInfo defaultInstance;

		public static WizardDataInfo getDefaultInstance() {
			return defaultInstance;
		}

		public WizardDataInfo getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.wizard.protobuf.data.WizardData.internal_static_WizardDataInfo_WizardDataInfo_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.wizard.protobuf.data.WizardData.internal_static_WizardDataInfo_WizardDataInfo_fieldAccessorTable;
		}

		private int bitField0_;
		// required int32 id = 1;
		public static final int ID_FIELD_NUMBER = 1;
		private int id_;

		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public int getId() {
			return id_;
		}

		// optional string name = 2;
		public static final int NAME_FIELD_NUMBER = 2;
		private java.lang.Object name_;

		public boolean hasName() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public String getName() {
			java.lang.Object ref = name_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					name_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// repeated string data = 3;
		public static final int DATA_FIELD_NUMBER = 3;
		private com.google.protobuf.LazyStringList data_;

		public java.util.List<String> getDataList() {
			return data_;
		}

		public int getDataCount() {
			return data_.size();
		}

		public String getData(int index) {
			return data_.get(index);
		}

		private void initFields() {
			id_ = 0;
			name_ = "";
			data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getNameBytes());
			}
			for (int i = 0; i < data_.size(); i++) {
				output.writeBytes(3, data_.getByteString(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getNameBytes());
			}
			{
				int dataSize = 0;
				for (int i = 0; i < data_.size(); i++) {
					dataSize += com.google.protobuf.CodedOutputStream
							.computeBytesSizeNoTag(data_.getByteString(i));
				}
				size += dataSize;
				size += 1 * getDataList().size();
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.wizard.protobuf.data.WizardData.WizardDataInfo parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.wizard.protobuf.data.WizardData.WizardDataInfo parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.wizard.protobuf.data.WizardData.WizardDataInfo parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static com.wizard.protobuf.data.WizardData.WizardDataInfo parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static com.wizard.protobuf.data.WizardData.WizardDataInfo parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.wizard.protobuf.data.WizardData.WizardDataInfo parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static com.wizard.protobuf.data.WizardData.WizardDataInfo parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.wizard.protobuf.data.WizardData.WizardDataInfo parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static com.wizard.protobuf.data.WizardData.WizardDataInfo parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static com.wizard.protobuf.data.WizardData.WizardDataInfo parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				com.wizard.protobuf.data.WizardData.WizardDataInfo prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.wizard.protobuf.data.WizardData.WizardDataInfoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.wizard.protobuf.data.WizardData.internal_static_WizardDataInfo_WizardDataInfo_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.wizard.protobuf.data.WizardData.internal_static_WizardDataInfo_WizardDataInfo_fieldAccessorTable;
			}

			// Construct using
			// com.wizard.protobuf.data.WizardData.WizardDataInfo.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				id_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				name_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.wizard.protobuf.data.WizardData.WizardDataInfo
						.getDescriptor();
			}

			public com.wizard.protobuf.data.WizardData.WizardDataInfo getDefaultInstanceForType() {
				return com.wizard.protobuf.data.WizardData.WizardDataInfo
						.getDefaultInstance();
			}

			public com.wizard.protobuf.data.WizardData.WizardDataInfo build() {
				com.wizard.protobuf.data.WizardData.WizardDataInfo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private com.wizard.protobuf.data.WizardData.WizardDataInfo buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				com.wizard.protobuf.data.WizardData.WizardDataInfo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public com.wizard.protobuf.data.WizardData.WizardDataInfo buildPartial() {
				com.wizard.protobuf.data.WizardData.WizardDataInfo result = new com.wizard.protobuf.data.WizardData.WizardDataInfo(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.name_ = name_;
				if (((bitField0_ & 0x00000004) == 0x00000004)) {
					data_ = new com.google.protobuf.UnmodifiableLazyStringList(
							data_);
					bitField0_ = (bitField0_ & ~0x00000004);
				}
				result.data_ = data_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.wizard.protobuf.data.WizardData.WizardDataInfo) {
					return mergeFrom((com.wizard.protobuf.data.WizardData.WizardDataInfo) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					com.wizard.protobuf.data.WizardData.WizardDataInfo other) {
				if (other == com.wizard.protobuf.data.WizardData.WizardDataInfo
						.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasName()) {
					setName(other.getName());
				}
				if (!other.data_.isEmpty()) {
					if (data_.isEmpty()) {
						data_ = other.data_;
						bitField0_ = (bitField0_ & ~0x00000004);
					} else {
						ensureDataIsMutable();
						data_.addAll(other.data_);
					}
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						id_ = input.readInt32();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						name_ = input.readBytes();
						break;
					}
					case 26: {
						ensureDataIsMutable();
						data_.add(input.readBytes());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required int32 id = 1;
			private int id_;

			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public int getId() {
				return id_;
			}

			public Builder setId(int value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = 0;
				onChanged();
				return this;
			}

			// optional string name = 2;
			private java.lang.Object name_ = "";

			public boolean hasName() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public String getName() {
				java.lang.Object ref = name_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setName(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				name_ = value;
				onChanged();
				return this;
			}

			public Builder clearName() {
				bitField0_ = (bitField0_ & ~0x00000002);
				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			void setName(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				name_ = value;
				onChanged();
			}

			// repeated string data = 3;
			private com.google.protobuf.LazyStringList data_ = com.google.protobuf.LazyStringArrayList.EMPTY;

			private void ensureDataIsMutable() {
				if (!((bitField0_ & 0x00000004) == 0x00000004)) {
					data_ = new com.google.protobuf.LazyStringArrayList(data_);
					bitField0_ |= 0x00000004;
				}
			}

			public java.util.List<String> getDataList() {
				return java.util.Collections.unmodifiableList(data_);
			}

			public int getDataCount() {
				return data_.size();
			}

			public String getData(int index) {
				return data_.get(index);
			}

			public Builder setData(int index, String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureDataIsMutable();
				data_.set(index, value);
				onChanged();
				return this;
			}

			public Builder addData(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureDataIsMutable();
				data_.add(value);
				onChanged();
				return this;
			}

			public Builder addAllData(java.lang.Iterable<String> values) {
				ensureDataIsMutable();
				super.addAll(values, data_);
				onChanged();
				return this;
			}

			public Builder clearData() {
				data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000004);
				onChanged();
				return this;
			}

			void addData(com.google.protobuf.ByteString value) {
				ensureDataIsMutable();
				data_.add(value);
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:WizardDataInfo.WizardDataInfo)
		}

		static {
			defaultInstance = new WizardDataInfo(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:WizardDataInfo.WizardDataInfo)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_WizardDataInfo_WizardDataInfo_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_WizardDataInfo_WizardDataInfo_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\024WizardDataInfo.proto\022\016WizardDataInfo\"8"
				+ "\n\016WizardDataInfo\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \001"
				+ "(\t\022\014\n\004data\030\003 \003(\tB&\n\030com.wizard.protobuf."
				+ "dataB\nWizardData" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_WizardDataInfo_WizardDataInfo_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_WizardDataInfo_WizardDataInfo_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_WizardDataInfo_WizardDataInfo_descriptor,
						new java.lang.String[] { "Id", "Name", "Data", },
						com.wizard.protobuf.data.WizardData.WizardDataInfo.class,
						com.wizard.protobuf.data.WizardData.WizardDataInfo.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
